#!/usr/bin/env python3
"""
Generate: Anxiety & Stress Management Workbook
By Daniel Tesfamariam
60-80 pages of CBT-based anxiety management content
"""

import os, sys
sys.path.insert(0, '/projects/sandbox/CLAUDE/etsy-digital-products-strategy')
_code = open('/projects/sandbox/CLAUDE/etsy-digital-products-strategy/generate_pdfs.py').read()
_code = _code.replace("\nif __name__ == '__main__':\n    main()\n", "\n")
exec(_code)


def _placeholder():
    pass  # Functions defined below



def add_chapter1(pdf):
    """Chapter 1: Understanding Anxiety (8 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 1: UNDERSTANDING ANXIETY")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Anxiety is your body's natural alarm system. It exists to protect you from")
    pdf.add_paragraph("danger. But when that alarm fires too often, too intensely, or without real")
    pdf.add_paragraph("threat, it becomes a problem that interferes with daily life.")
    pdf.add_blank_line()

    pdf.add_heading2("What Is Anxiety?")
    pdf.add_blank_line()
    pdf.add_paragraph("Anxiety is a future-focused emotional state characterized by worry, dread,")
    pdf.add_paragraph("and physical tension about anticipated threats or uncertain outcomes.")
    pdf.add_blank_line()
    pdf.add_paragraph("KEY DISTINCTION:")
    pdf.add_bullet("FEAR = Response to immediate, present danger (a car swerving toward you)")
    pdf.add_bullet("ANXIETY = Response to anticipated, future threat (worrying about a presentation)")
    pdf.add_blank_line()
    pdf.add_paragraph("Some anxiety is normal and even helpful -- it motivates preparation and")
    pdf.add_paragraph("keeps us alert. It becomes a problem when it is disproportionate to the")
    pdf.add_paragraph("actual threat, persistent, and interferes with daily functioning.")
    pdf.add_blank_line()

    pdf.add_heading2("Types of Anxiety Disorders")
    pdf.add_blank_line()
    pdf.add_heading3("GENERALIZED ANXIETY DISORDER (GAD)")
    pdf.add_bullet("Excessive worry about multiple areas of life (work, health, family)")
    pdf.add_bullet("Difficulty controlling the worry")
    pdf.add_bullet("Present most days for 6+ months")
    pdf.add_bullet("Accompanied by physical symptoms (muscle tension, fatigue, restlessness)")
    pdf.add_blank_line()

    pdf.add_heading3("SOCIAL ANXIETY DISORDER")
    pdf.add_bullet("Intense fear of social situations and being judged")
    pdf.add_bullet("Avoidance of public speaking, meeting new people, eating in public")
    pdf.add_bullet("Physical symptoms in social settings (blushing, sweating, trembling)")
    pdf.add_bullet("Fear is disproportionate to actual social threat")
    pdf.add_blank_line()

    pdf.add_heading3("PANIC DISORDER")
    pdf.add_bullet("Recurrent unexpected panic attacks (sudden surge of intense fear)")
    pdf.add_bullet("Physical symptoms: racing heart, chest pain, difficulty breathing")
    pdf.add_bullet("Fear of having another attack")
    pdf.add_bullet("May lead to avoidance of situations where attacks occurred")
    pdf.add_blank_line()

    pdf.add_heading3("SPECIFIC PHOBIAS")
    pdf.add_bullet("Intense fear of a specific object or situation")
    pdf.add_bullet("Common: heights, flying, spiders, blood, enclosed spaces")
    pdf.add_bullet("Avoidance or endured with extreme distress")
    pdf.add_bullet("Fear is out of proportion to actual danger")
    pdf.add_blank_line()

    pdf.add_heading3("HEALTH ANXIETY (Illness Anxiety Disorder)")
    pdf.add_bullet("Preoccupation with having or developing a serious illness")
    pdf.add_bullet("Excessive checking of body for signs of disease")
    pdf.add_bullet("Frequent doctor visits or complete avoidance of medical care")
    pdf.add_bullet("Reassurance provides only temporary relief")
    pdf.add_blank_line()

    pdf.add_heading2("The Fight-Flight-Freeze Response Explained")
    pdf.add_blank_line()
    pdf.add_paragraph("When your brain perceives danger (real or imagined), it activates the")
    pdf.add_paragraph("sympathetic nervous system. This triggers a cascade of physical changes:")
    pdf.add_blank_line()

    pdf.add_heading3("FIGHT RESPONSE:")
    pdf.add_bullet("Muscle tension, jaw clenching, fists tightening")
    pdf.add_bullet("Anger, irritability, desire to argue or confront")
    pdf.add_bullet("Feeling 'on edge' or ready to snap")
    pdf.add_bullet("Purpose: Prepare body to defend against threat")
    pdf.add_blank_line()

    pdf.add_heading3("FLIGHT RESPONSE:")
    pdf.add_bullet("Restlessness, urge to escape or avoid")
    pdf.add_bullet("Racing thoughts, inability to sit still")
    pdf.add_bullet("Avoiding situations, canceling plans")
    pdf.add_bullet("Purpose: Prepare body to run from threat")
    pdf.add_blank_line()

    pdf.add_heading3("FREEZE RESPONSE:")
    pdf.add_bullet("Feeling stuck, paralyzed, unable to make decisions")
    pdf.add_bullet("Dissociation, numbness, feeling 'checked out'")
    pdf.add_bullet("Difficulty speaking or moving")
    pdf.add_bullet("Purpose: Become invisible to threat (play dead)")
    pdf.add_blank_line()

    pdf.add_paragraph("IMPORTANT: None of these responses are 'wrong.' They are automatic")
    pdf.add_paragraph("survival mechanisms. The goal is not to eliminate them, but to help")
    pdf.add_paragraph("your nervous system accurately assess actual danger levels.")
    pdf.add_blank_line()

    pdf.add_heading2("Physical Symptoms of Anxiety Checklist")
    pdf.add_blank_line()
    pdf.add_paragraph("Check all symptoms you experience regularly:")
    pdf.add_blank_line()
    pdf.add_heading3("HEAD & MIND:")
    pdf.add_bullet("[ ] Racing thoughts or mind going blank")
    pdf.add_bullet("[ ] Difficulty concentrating")
    pdf.add_bullet("[ ] Headaches or pressure in head")
    pdf.add_bullet("[ ] Dizziness or lightheadedness")
    pdf.add_bullet("[ ] Feeling detached from reality (derealization)")
    pdf.add_blank_line()

    pdf.add_heading3("CHEST & BREATHING:")
    pdf.add_bullet("[ ] Rapid heartbeat or heart pounding")
    pdf.add_bullet("[ ] Chest tightness or pain")
    pdf.add_bullet("[ ] Shortness of breath")
    pdf.add_bullet("[ ] Feeling like you cannot get enough air")
    pdf.add_bullet("[ ] Hyperventilation")
    pdf.add_blank_line()

    pdf.add_heading3("STOMACH & DIGESTION:")
    pdf.add_bullet("[ ] Nausea or stomach churning")
    pdf.add_bullet("[ ] Loss of appetite or overeating")
    pdf.add_bullet("[ ] Diarrhea or constipation")
    pdf.add_bullet("[ ] Butterflies or knots in stomach")
    pdf.add_blank_line()

    pdf.add_heading3("MUSCLES & BODY:")
    pdf.add_bullet("[ ] Muscle tension (especially neck, shoulders, jaw)")
    pdf.add_bullet("[ ] Trembling or shaking")
    pdf.add_bullet("[ ] Sweating (palms, underarms, forehead)")
    pdf.add_bullet("[ ] Hot flashes or chills")
    pdf.add_bullet("[ ] Tingling or numbness in hands/feet")
    pdf.add_bullet("[ ] Fatigue and exhaustion")
    pdf.add_blank_line()

    pdf.add_heading3("SLEEP & ENERGY:")
    pdf.add_bullet("[ ] Difficulty falling asleep")
    pdf.add_bullet("[ ] Waking up in the middle of the night")
    pdf.add_bullet("[ ] Waking up feeling unrested")
    pdf.add_bullet("[ ] Nightmares or anxious dreams")
    pdf.add_bullet("[ ] Constant fatigue despite sleeping")
    pdf.add_blank_line()

    pdf.add_paragraph("Total symptoms checked: _____ / 24")
    pdf.add_paragraph("0-5: Mild anxiety symptoms")
    pdf.add_paragraph("6-12: Moderate anxiety symptoms - consider professional support")
    pdf.add_paragraph("13+: Significant anxiety symptoms - strongly recommend professional help")
    pdf.add_blank_line()

    pdf.add_heading2("When Anxiety Becomes a Disorder")
    pdf.add_blank_line()
    pdf.add_paragraph("Normal anxiety becomes a disorder when it meets these criteria:")
    pdf.add_blank_line()
    pdf.add_bullet("1. INTENSITY: Anxiety is out of proportion to the actual situation")
    pdf.add_bullet("2. DURATION: Persists for weeks or months (not just a stressful day)")
    pdf.add_bullet("3. INTERFERENCE: Affects work, relationships, or daily activities")
    pdf.add_bullet("4. AVOIDANCE: You change your behavior to avoid anxiety triggers")
    pdf.add_bullet("5. DISTRESS: Causes significant emotional suffering")
    pdf.add_blank_line()
    pdf.add_paragraph("SELF-ASSESSMENT: Rate each area 1-10 (10 = severely impacted)")
    pdf.add_paragraph("  How much does anxiety affect your work/school? ___/10")
    pdf.add_paragraph("  How much does anxiety affect your relationships? ___/10")
    pdf.add_paragraph("  How much does anxiety affect your physical health? ___/10")
    pdf.add_paragraph("  How much does anxiety affect your enjoyment of life? ___/10")
    pdf.add_paragraph("  How many activities do you avoid due to anxiety? ___/10")
    pdf.add_paragraph("  TOTAL: ___/50")
    pdf.add_blank_line()
    pdf.add_paragraph("If your total is 25 or higher, professional support is strongly recommended.")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 1")
    pdf.add_separator()
    pdf.add_bullet("[ ] Complete the physical symptoms checklist above")
    pdf.add_bullet("[ ] Identify which anxiety type most matches your experience")
    pdf.add_bullet("[ ] Notice your default stress response (fight/flight/freeze)")
    pdf.add_bullet("[ ] Complete the self-assessment scoring")
    pdf.add_bullet("[ ] If score is 25+, research therapists in your area")
    pdf.add_bullet("[ ] Begin noticing when anxiety shows up (just notice, no judgment)")
    pdf.add_blank_line()



def add_chapter2(pdf):
    """Chapter 2: CBT Thought Records (12 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 2: CBT THOUGHT RECORDS")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Cognitive Behavioral Therapy (CBT) is the gold standard treatment for")
    pdf.add_paragraph("anxiety. Its core principle: your thoughts create your feelings. By")
    pdf.add_paragraph("identifying and challenging unhelpful thoughts, you can change how you feel.")
    pdf.add_blank_line()

    pdf.add_heading2("The Situation-Thought-Emotion-Behavior Model")
    pdf.add_blank_line()
    pdf.add_paragraph("Every emotional experience follows this chain:")
    pdf.add_blank_line()
    pdf.add_paragraph("SITUATION (What happened)")
    pdf.add_paragraph("  -> THOUGHT (What you told yourself about it)")
    pdf.add_paragraph("    -> EMOTION (What you felt)")
    pdf.add_paragraph("      -> BEHAVIOR (What you did)")
    pdf.add_blank_line()
    pdf.add_paragraph("EXAMPLE:")
    pdf.add_paragraph("  Situation: Boss asks to see you in their office")
    pdf.add_paragraph("  Thought: 'I must be in trouble. I'm going to get fired.'")
    pdf.add_paragraph("  Emotion: Panic (9/10), dread (8/10)")
    pdf.add_paragraph("  Behavior: Heart races, rehearse excuses, consider calling in sick")
    pdf.add_blank_line()
    pdf.add_paragraph("ALTERNATIVE:")
    pdf.add_paragraph("  Situation: Boss asks to see you in their office")
    pdf.add_paragraph("  Thought: 'Could be anything. Maybe they have a new project for me.'")
    pdf.add_paragraph("  Emotion: Mild curiosity (3/10 anxiety)")
    pdf.add_paragraph("  Behavior: Walk calmly to their office")
    pdf.add_blank_line()
    pdf.add_paragraph("Same situation, completely different experience -- because of the THOUGHT.")
    pdf.add_blank_line()

    pdf.add_heading2("15 Common Cognitive Distortions")
    pdf.add_blank_line()
    pdf.add_paragraph("Cognitive distortions are habitual thinking errors that fuel anxiety.")
    pdf.add_paragraph("Learning to spot them is the first step to challenging them.")
    pdf.add_blank_line()

    pdf.add_heading3("1. ALL-OR-NOTHING THINKING")
    pdf.add_paragraph("   Seeing things in black and white, no middle ground.")
    pdf.add_paragraph("   Example: 'If I don't get 100%, I'm a total failure.'")
    pdf.add_blank_line()

    pdf.add_heading3("2. CATASTROPHIZING")
    pdf.add_paragraph("   Jumping to the worst possible outcome.")
    pdf.add_paragraph("   Example: 'This headache is probably a brain tumor.'")
    pdf.add_blank_line()

    pdf.add_heading3("3. MIND READING")
    pdf.add_paragraph("   Assuming you know what others are thinking (usually negative).")
    pdf.add_paragraph("   Example: 'Everyone at that party thought I was boring.'")
    pdf.add_blank_line()

    pdf.add_heading3("4. FORTUNE TELLING")
    pdf.add_paragraph("   Predicting the future will be negative without evidence.")
    pdf.add_paragraph("   Example: 'This interview will definitely go badly.'")
    pdf.add_blank_line()

    pdf.add_heading3("5. OVERGENERALIZATION")
    pdf.add_paragraph("   One negative event becomes a never-ending pattern.")
    pdf.add_paragraph("   Example: 'I failed one test. I'll never pass anything.'")
    pdf.add_blank_line()

    pdf.add_heading3("6. MENTAL FILTER")
    pdf.add_paragraph("   Focusing only on negatives, ignoring positives.")
    pdf.add_paragraph("   Example: Getting 49 positive reviews and fixating on 1 negative.")
    pdf.add_blank_line()

    pdf.add_heading3("7. DISCOUNTING THE POSITIVE")
    pdf.add_paragraph("   Dismissing good things as 'not counting.'")
    pdf.add_paragraph("   Example: 'They only said nice things because they felt sorry for me.'")
    pdf.add_blank_line()

    pdf.add_heading3("8. SHOULD STATEMENTS")
    pdf.add_paragraph("   Rigid rules about how you/others/the world 'should' be.")
    pdf.add_paragraph("   Example: 'I should always be productive. I should never make mistakes.'")
    pdf.add_blank_line()

    pdf.add_heading3("9. EMOTIONAL REASONING")
    pdf.add_paragraph("   Believing something is true because you feel it.")
    pdf.add_paragraph("   Example: 'I feel like a fraud, so I must be one.'")
    pdf.add_blank_line()

    pdf.add_heading3("10. LABELING")
    pdf.add_paragraph("   Attaching a fixed, global label to yourself or others.")
    pdf.add_paragraph("   Example: 'I'm an idiot' instead of 'I made a mistake.'")
    pdf.add_blank_line()

    pdf.add_heading3("11. PERSONALIZATION")
    pdf.add_paragraph("   Blaming yourself for things outside your control.")
    pdf.add_paragraph("   Example: 'My friend is upset -- it must be something I did.'")
    pdf.add_blank_line()

    pdf.add_heading3("12. MAGNIFICATION / MINIMIZATION")
    pdf.add_paragraph("   Making negatives bigger and positives smaller.")
    pdf.add_paragraph("   Example: 'My tiny mistake will ruin everything' / 'My achievement was luck.'")
    pdf.add_blank_line()

    pdf.add_heading3("13. CONTROL FALLACIES")
    pdf.add_paragraph("   Feeling responsible for everything OR helpless about everything.")
    pdf.add_paragraph("   Example: 'If I don't manage every detail, everything falls apart.'")
    pdf.add_blank_line()

    pdf.add_heading3("14. FALLACY OF FAIRNESS")
    pdf.add_paragraph("   Expecting life to always be fair and being distressed when it is not.")
    pdf.add_paragraph("   Example: 'It's not fair they got promoted over me -- I deserve it more.'")
    pdf.add_blank_line()

    pdf.add_heading3("15. BLAMING")
    pdf.add_paragraph("   Holding others entirely responsible for your emotional pain.")
    pdf.add_paragraph("   Example: 'You make me anxious' instead of 'I feel anxious around you.'")
    pdf.add_blank_line()

    pdf.add_paragraph("MY TOP 3 DISTORTIONS (the ones I use most often):")
    pdf.add_paragraph("  1. _______________________________________________________")
    pdf.add_paragraph("  2. _______________________________________________________")
    pdf.add_paragraph("  3. _______________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("Thought Challenging Questions")
    pdf.add_blank_line()
    pdf.add_paragraph("When you catch an anxious thought, ask yourself these questions:")
    pdf.add_blank_line()
    pdf.add_bullet("1. What is the evidence FOR this thought?")
    pdf.add_bullet("2. What is the evidence AGAINST this thought?")
    pdf.add_bullet("3. What cognitive distortion might I be using?")
    pdf.add_bullet("4. What would I tell a friend who had this thought?")
    pdf.add_bullet("5. What is the most realistic outcome (not worst, not best)?")
    pdf.add_bullet("6. Will this matter in 5 years? 5 months? 5 weeks?")
    pdf.add_bullet("7. Am I confusing a thought with a fact?")
    pdf.add_bullet("8. What is a more balanced way to look at this?")
    pdf.add_bullet("9. If the worst did happen, could I cope?")
    pdf.add_bullet("10. What has actually happened in similar situations before?")
    pdf.add_blank_line()


    pdf.add_heading2("Thought Record Worksheets")
    pdf.add_blank_line()
    pdf.add_paragraph("Complete one thought record each time you notice significant anxiety.")
    pdf.add_paragraph("Over time, you will start to see patterns in your thinking.")
    pdf.add_blank_line()

    for i in range(1, 11):
        pdf.add_heading3(f"THOUGHT RECORD #{i}")
        pdf.add_blank_line()
        pdf.add_paragraph(f"Date: ________________  Time: ________  Anxiety Level (0-10): ___")
        pdf.add_blank_line()
        pdf.add_paragraph("SITUATION (What happened? Where were you? Who was there?)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("AUTOMATIC THOUGHT (What went through your mind?)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("COGNITIVE DISTORTION (Which thinking error? See list above)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("EMOTION (What did you feel? Rate intensity 0-10)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("EVIDENCE FOR the thought:")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("EVIDENCE AGAINST the thought:")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("BALANCED/ALTERNATIVE THOUGHT:")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("NEW EMOTION after reframing (0-10): ___")
        pdf.add_separator()
        pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 2")
    pdf.add_separator()
    pdf.add_bullet("[ ] Read through all 15 cognitive distortions")
    pdf.add_bullet("[ ] Identify your top 3 most common distortions")
    pdf.add_bullet("[ ] Complete at least 1 thought record today")
    pdf.add_bullet("[ ] Aim for 1 thought record per day for the next week")
    pdf.add_bullet("[ ] Practice the 10 challenging questions on your next anxious thought")
    pdf.add_bullet("[ ] Notice: Do your anxiety ratings decrease after reframing?")
    pdf.add_blank_line()



def add_chapter3(pdf):
    """Chapter 3: Breathing & Grounding Techniques (8 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 3: BREATHING & GROUNDING TECHNIQUES")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("When anxiety strikes, your body enters survival mode. These techniques")
    pdf.add_paragraph("activate your parasympathetic nervous system (the 'rest and digest'")
    pdf.add_paragraph("system) to physically calm your body within minutes.")
    pdf.add_blank_line()

    pdf.add_heading2("Box Breathing (4-4-4-4)")
    pdf.add_blank_line()
    pdf.add_paragraph("Used by Navy SEALs to stay calm under extreme pressure.")
    pdf.add_blank_line()
    pdf.add_paragraph("HOW TO DO IT:")
    pdf.add_bullet("1. INHALE through your nose for 4 seconds")
    pdf.add_bullet("2. HOLD your breath for 4 seconds")
    pdf.add_bullet("3. EXHALE through your mouth for 4 seconds")
    pdf.add_bullet("4. HOLD (lungs empty) for 4 seconds")
    pdf.add_bullet("5. Repeat 4-8 times")
    pdf.add_blank_line()
    pdf.add_paragraph("WHEN TO USE: Before stressful situations, during panic, at bedtime.")
    pdf.add_paragraph("PRACTICE LOG:")
    pdf.add_paragraph("  Date: _______ Rounds: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_paragraph("  Date: _______ Rounds: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_paragraph("  Date: _______ Rounds: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_blank_line()

    pdf.add_heading2("4-7-8 Breathing Technique")
    pdf.add_blank_line()
    pdf.add_paragraph("Developed by Dr. Andrew Weil. Especially effective for sleep anxiety.")
    pdf.add_blank_line()
    pdf.add_paragraph("HOW TO DO IT:")
    pdf.add_bullet("1. Place tongue tip behind upper front teeth")
    pdf.add_bullet("2. EXHALE completely through mouth (whoosh sound)")
    pdf.add_bullet("3. INHALE quietly through nose for 4 seconds")
    pdf.add_bullet("4. HOLD breath for 7 seconds")
    pdf.add_bullet("5. EXHALE completely through mouth for 8 seconds (whoosh)")
    pdf.add_bullet("6. Repeat 4 cycles")
    pdf.add_blank_line()
    pdf.add_paragraph("NOTE: The ratio matters more than exact seconds. If 4-7-8 feels too")
    pdf.add_paragraph("long, start with 2-3.5-4 and work up. The key is the long exhale.")
    pdf.add_blank_line()
    pdf.add_paragraph("PRACTICE LOG:")
    pdf.add_paragraph("  Date: _______ Cycles: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_paragraph("  Date: _______ Cycles: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_paragraph("  Date: _______ Cycles: ___ Anxiety before: ___/10  After: ___/10")
    pdf.add_blank_line()

    pdf.add_heading2("5-4-3-2-1 Grounding Technique")
    pdf.add_blank_line()
    pdf.add_paragraph("This technique brings you back to the present moment using your 5 senses.")
    pdf.add_paragraph("Excellent for dissociation, panic attacks, and overwhelming anxiety.")
    pdf.add_blank_line()
    pdf.add_paragraph("IDENTIFY:")
    pdf.add_blank_line()
    pdf.add_paragraph("5 things you can SEE:")
    pdf.add_paragraph("  1. _________________ 2. _________________ 3. _________________")
    pdf.add_paragraph("  4. _________________ 5. _________________")
    pdf.add_blank_line()
    pdf.add_paragraph("4 things you can TOUCH/FEEL:")
    pdf.add_paragraph("  1. _________________ 2. _________________ 3. _________________")
    pdf.add_paragraph("  4. _________________")
    pdf.add_blank_line()
    pdf.add_paragraph("3 things you can HEAR:")
    pdf.add_paragraph("  1. _________________ 2. _________________ 3. _________________")
    pdf.add_blank_line()
    pdf.add_paragraph("2 things you can SMELL:")
    pdf.add_paragraph("  1. _________________ 2. _________________")
    pdf.add_blank_line()
    pdf.add_paragraph("1 thing you can TASTE:")
    pdf.add_paragraph("  1. _________________")
    pdf.add_blank_line()
    pdf.add_paragraph("TIP: Keep a grounding kit nearby (textured object, essential oil,")
    pdf.add_paragraph("mint candy, photo of safe place) for quick sensory access.")
    pdf.add_blank_line()

    pdf.add_heading2("Progressive Muscle Relaxation (PMR) Script")
    pdf.add_blank_line()
    pdf.add_paragraph("PMR works by tensing and releasing muscle groups, teaching your body")
    pdf.add_paragraph("the difference between tension and relaxation. Takes 10-15 minutes.")
    pdf.add_blank_line()
    pdf.add_paragraph("INSTRUCTIONS: For each group, TENSE for 5 seconds, then RELEASE for 10.")
    pdf.add_paragraph("Focus on the contrast between tension and relaxation.")
    pdf.add_blank_line()
    pdf.add_bullet("1. HANDS: Make tight fists. Hold 5 seconds. Release. Notice warmth.")
    pdf.add_bullet("2. FOREARMS: Bend wrists back (stretch forearms). Hold. Release.")
    pdf.add_bullet("3. BICEPS: Curl arms up tight. Hold. Release. Let arms hang heavy.")
    pdf.add_bullet("4. SHOULDERS: Shrug shoulders up to ears. Hold. Drop them down.")
    pdf.add_bullet("5. FOREHEAD: Raise eyebrows as high as possible. Hold. Smooth out.")
    pdf.add_bullet("6. EYES/CHEEKS: Squeeze eyes shut tight. Hold. Relax face completely.")
    pdf.add_bullet("7. JAW: Clench jaw tightly. Hold. Let mouth fall slightly open.")
    pdf.add_bullet("8. NECK: Press head back gently against chair. Hold. Release.")
    pdf.add_bullet("9. CHEST: Take deep breath, hold it. Release all air. Breathe normally.")
    pdf.add_bullet("10. STOMACH: Tighten abs as if bracing for a punch. Hold. Soften.")
    pdf.add_bullet("11. GLUTES: Squeeze buttocks together. Hold. Release into chair.")
    pdf.add_bullet("12. THIGHS: Press legs together firmly. Hold. Let them fall apart.")
    pdf.add_bullet("13. CALVES: Point toes up toward shins. Hold. Release.")
    pdf.add_bullet("14. FEET: Curl toes under tightly. Hold. Spread toes wide. Relax.")
    pdf.add_blank_line()
    pdf.add_paragraph("After completing all groups, do a body scan from head to toe.")
    pdf.add_paragraph("Notice any remaining tension. Breathe into those areas.")
    pdf.add_blank_line()

    pdf.add_heading2("Body Scan Meditation Guide")
    pdf.add_blank_line()
    pdf.add_paragraph("A gentler alternative to PMR. Simply notice sensations without changing them.")
    pdf.add_paragraph("Duration: 5-20 minutes. Best done lying down.")
    pdf.add_blank_line()
    pdf.add_paragraph("SCRIPT (read slowly, pausing between each area):")
    pdf.add_blank_line()
    pdf.add_paragraph("Close your eyes. Take three slow, deep breaths.")
    pdf.add_paragraph("Bring attention to the top of your head. Notice any sensations.")
    pdf.add_paragraph("Move attention to your forehead... your eyes... your cheeks... your jaw.")
    pdf.add_paragraph("Notice your neck and throat. Is there tightness? Just notice.")
    pdf.add_paragraph("Bring awareness to your shoulders. Let them soften if they want to.")
    pdf.add_paragraph("Move down your arms... elbows... wrists... hands... fingertips.")
    pdf.add_paragraph("Notice your upper back... middle back... lower back.")
    pdf.add_paragraph("Bring attention to your chest and the rhythm of breathing.")
    pdf.add_paragraph("Notice your stomach rising and falling.")
    pdf.add_paragraph("Move to your hips... thighs... knees... calves... ankles...")
    pdf.add_paragraph("Notice your feet... the soles... each toe.")
    pdf.add_paragraph("Now feel your whole body at once, breathing as one.")
    pdf.add_paragraph("When ready, slowly open your eyes.")
    pdf.add_blank_line()

    pdf.add_heading2("Emergency Calm-Down Protocol")
    pdf.add_blank_line()
    pdf.add_paragraph("When anxiety hits hard and you need to calm down NOW (under 2 minutes):")
    pdf.add_blank_line()
    pdf.add_bullet("1. SPLASH cold water on your face or hold ice cubes (activates dive reflex)")
    pdf.add_bullet("2. BREATHE: Exhale longer than you inhale (4 in, 8 out)")
    pdf.add_bullet("3. GROUND: Press feet firmly into floor, name 5 things you see")
    pdf.add_bullet("4. MOVE: Walk briskly, do jumping jacks, or shake your hands")
    pdf.add_bullet("5. SELF-TALK: 'This is anxiety. It cannot hurt me. It will pass.'")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 3")
    pdf.add_separator()
    pdf.add_bullet("[ ] Practice box breathing 3 times today (before meals is easy to remember)")
    pdf.add_bullet("[ ] Try the 5-4-3-2-1 grounding exercise right now")
    pdf.add_bullet("[ ] Do the full PMR script once this week (before bed works well)")
    pdf.add_bullet("[ ] Create a 'grounding kit' for quick access during anxiety spikes")
    pdf.add_bullet("[ ] Write the Emergency Calm-Down Protocol on an index card for your wallet")
    pdf.add_bullet("[ ] Track your practice in the logs above for 1 week")
    pdf.add_blank_line()



def add_chapter4(pdf):
    """Chapter 4: Worry Management System (10 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 4: WORRY MANAGEMENT SYSTEM")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Chronic worrying feels productive but rarely is. This chapter gives you")
    pdf.add_paragraph("a structured system to contain worry, distinguish productive from")
    pdf.add_paragraph("unproductive worry, and break the cycle of rumination.")
    pdf.add_blank_line()

    pdf.add_heading2("The Worry Time Technique")
    pdf.add_blank_line()
    pdf.add_paragraph("Instead of worrying all day, designate a specific 'worry time' each day.")
    pdf.add_paragraph("This contains worry to a controlled period and frees the rest of your day.")
    pdf.add_blank_line()
    pdf.add_paragraph("HOW IT WORKS:")
    pdf.add_bullet("1. Choose a daily 15-minute 'worry time' (not before bed)")
    pdf.add_bullet("2. When a worry pops up during the day, write it down briefly")
    pdf.add_bullet("3. Tell yourself: 'I'll think about this during worry time'")
    pdf.add_bullet("4. During worry time, review your list and worry intentionally")
    pdf.add_bullet("5. After 15 minutes, STOP. Close the list until tomorrow.")
    pdf.add_blank_line()
    pdf.add_paragraph("My designated worry time: ___:___ AM/PM")
    pdf.add_paragraph("Location: ___________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("WHY THIS WORKS:")
    pdf.add_bullet("You are not suppressing worries (which makes them worse)")
    pdf.add_bullet("You are POSTPONING them to a controlled time")
    pdf.add_bullet("Most worries feel less urgent when you return to them later")
    pdf.add_bullet("It breaks the habit of 24/7 worry")
    pdf.add_blank_line()

    pdf.add_heading2("Productive vs. Unproductive Worry")
    pdf.add_blank_line()
    pdf.add_paragraph("Not all worry is useless. The key is distinguishing between the two types:")
    pdf.add_blank_line()
    pdf.add_heading3("PRODUCTIVE WORRY:")
    pdf.add_bullet("About something you CAN control or influence")
    pdf.add_bullet("Leads to a specific action step")
    pdf.add_bullet("Has a realistic chance of happening")
    pdf.add_bullet("You can do something about it RIGHT NOW or very soon")
    pdf.add_blank_line()
    pdf.add_paragraph("Example: 'I'm worried about my presentation tomorrow.'")
    pdf.add_paragraph("Action: Practice it 3 more times tonight. Prepare backup slides.")
    pdf.add_blank_line()
    pdf.add_heading3("UNPRODUCTIVE WORRY:")
    pdf.add_bullet("About something you CANNOT control")
    pdf.add_bullet("Does not lead to any action (just circular thinking)")
    pdf.add_bullet("About very unlikely worst-case scenarios")
    pdf.add_bullet("About the past (which cannot be changed)")
    pdf.add_blank_line()
    pdf.add_paragraph("Example: 'What if there's an earthquake during my vacation?'")
    pdf.add_paragraph("Action: None possible. This is unproductive worry.")
    pdf.add_blank_line()

    pdf.add_heading2("Worry Decision Tree")
    pdf.add_blank_line()
    pdf.add_paragraph("Use this flowchart for every worry that pops up:")
    pdf.add_blank_line()
    pdf.add_paragraph("START: What am I worried about?")
    pdf.add_paragraph("  |")
    pdf.add_paragraph("  v")
    pdf.add_paragraph("Q1: Is this something I can control or influence?")
    pdf.add_paragraph("  |              |")
    pdf.add_paragraph("  YES            NO")
    pdf.add_paragraph("  |              |")
    pdf.add_paragraph("  v              v")
    pdf.add_paragraph("Q2: Can I take   STOP. This is unproductive worry.")
    pdf.add_paragraph("action NOW?      Use: acceptance, grounding, or")
    pdf.add_paragraph("  |              distraction technique.")
    pdf.add_paragraph("  YES    NO")
    pdf.add_paragraph("  |      |")
    pdf.add_paragraph("  v      v")
    pdf.add_paragraph("DO IT.   SCHEDULE it. Write the action")
    pdf.add_paragraph("Take     and date in your planner.")
    pdf.add_paragraph("action   Then LET IT GO until that time.")
    pdf.add_paragraph("now.")
    pdf.add_blank_line()

    pdf.add_heading2("The Catastrophizing Ladder")
    pdf.add_blank_line()
    pdf.add_paragraph("When your mind jumps to the worst case, use this ladder to find")
    pdf.add_paragraph("the realistic middle ground between best and worst outcomes:")
    pdf.add_blank_line()
    pdf.add_paragraph("MY WORRY: ___________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("WORST CASE (What my anxious brain says will happen):")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("Likelihood (0-100%): ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("BEST CASE (Ideal outcome):")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("Likelihood (0-100%): ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("MOST LIKELY CASE (What will probably actually happen):")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("Likelihood (0-100%): ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("IF the worst DID happen, could I cope? How?")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("What has happened in similar situations in the past?")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_separator()
    pdf.add_blank_line()

    # Additional catastrophizing ladder blanks
    pdf.add_paragraph("CATASTROPHIZING LADDER #2")
    pdf.add_blank_line()
    pdf.add_paragraph("MY WORRY: ___________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("WORST CASE: __________________________________________________")
    pdf.add_paragraph("Likelihood: ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("BEST CASE: ___________________________________________________")
    pdf.add_paragraph("Likelihood: ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("MOST LIKELY: _________________________________________________")
    pdf.add_paragraph("Likelihood: ____%")
    pdf.add_blank_line()
    pdf.add_paragraph("Coping plan if worst happens: _________________________________")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_separator()

    pdf.add_heading2("Worry Journal Pages")
    pdf.add_blank_line()
    pdf.add_paragraph("Use these during your designated worry time:")
    pdf.add_blank_line()

    for day in range(1, 8):
        pdf.add_heading3(f"WORRY TIME - DAY {day}")
        pdf.add_paragraph(f"Date: ________________  Time: ________")
        pdf.add_blank_line()
        pdf.add_paragraph("Worry #1: _________________________________________________")
        pdf.add_paragraph("  Productive or Unproductive? (circle one)")
        pdf.add_paragraph("  Action to take (if productive): __________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("Worry #2: _________________________________________________")
        pdf.add_paragraph("  Productive or Unproductive? (circle one)")
        pdf.add_paragraph("  Action to take (if productive): __________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("Worry #3: _________________________________________________")
        pdf.add_paragraph("  Productive or Unproductive? (circle one)")
        pdf.add_paragraph("  Action to take (if productive): __________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("Overall anxiety after worry time (0-10): ___")
        pdf.add_separator()
        pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 4")
    pdf.add_separator()
    pdf.add_bullet("[ ] Choose your daily worry time (15 minutes, not before bed)")
    pdf.add_bullet("[ ] Start writing down worries as they come up during the day")
    pdf.add_bullet("[ ] Practice the worry decision tree on your top 3 current worries")
    pdf.add_bullet("[ ] Complete one catastrophizing ladder for your biggest worry")
    pdf.add_bullet("[ ] Use the worry journal pages for 7 consecutive days")
    pdf.add_bullet("[ ] Notice: How many of your worries are unproductive?")
    pdf.add_blank_line()



def add_chapter5(pdf):
    """Chapter 5: Daily Anxiety Tracker (12 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 5: DAILY ANXIETY TRACKER")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Tracking your anxiety reveals patterns you cannot see in the moment.")
    pdf.add_paragraph("After 30 days of tracking, you will know your triggers, your worst times,")
    pdf.add_paragraph("and which coping strategies actually work for you.")
    pdf.add_blank_line()

    pdf.add_heading2("How to Use This Tracker")
    pdf.add_blank_line()
    pdf.add_bullet("Fill in one row per day (takes 2-3 minutes)")
    pdf.add_bullet("Rate anxiety on 0-10 scale (0=none, 5=moderate, 10=extreme)")
    pdf.add_bullet("Note your primary trigger and coping strategy used")
    pdf.add_bullet("Rate sleep quality (1=terrible, 5=excellent)")
    pdf.add_bullet("At end of each week, complete the Weekly Pattern Review")
    pdf.add_blank_line()

    pdf.add_heading2("30-Day Anxiety Tracker")
    pdf.add_blank_line()

    # Week headers and daily rows
    for week in range(1, 5):
        pdf.add_heading3(f"WEEK {week}")
        pdf.add_blank_line()
        pdf.add_paragraph("Day | Date    | Anxiety | Trigger          | Coping Used      | Sleep")
        pdf.add_paragraph("----|---------|---------|------------------|------------------|------")
        for day in range(1, 8):
            day_num = (week - 1) * 7 + day
            if day_num <= 30:
                pdf.add_paragraph(f" {day_num:2d} | _______ | ___/10  | ________________ | ________________ | __/5")
        pdf.add_blank_line()

        # Weekly review
        pdf.add_heading3(f"WEEK {week} - PATTERN REVIEW")
        pdf.add_blank_line()
        pdf.add_paragraph("Average anxiety level this week: ___/10")
        pdf.add_paragraph("Highest anxiety day: ____________ (What happened?)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_paragraph("Lowest anxiety day: _____________ (What was different?)")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_paragraph("Most common trigger: ___________________________________________")
        pdf.add_paragraph("Most effective coping strategy: _________________________________")
        pdf.add_paragraph("Average sleep quality: ___/5")
        pdf.add_paragraph("Pattern I notice: ______________________________________________")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_paragraph("What I want to try differently next week:")
        pdf.add_paragraph("_______________________________________________________________")
        pdf.add_blank_line()
        pdf.add_separator()
        pdf.add_blank_line()

    # Day 29-30 overflow
    pdf.add_heading3("DAYS 29-30")
    pdf.add_paragraph("Day | Date    | Anxiety | Trigger          | Coping Used      | Sleep")
    pdf.add_paragraph("----|---------|---------|------------------|------------------|------")
    pdf.add_paragraph(" 29 | _______ | ___/10  | ________________ | ________________ | __/5")
    pdf.add_paragraph(" 30 | _______ | ___/10  | ________________ | ________________ | __/5")
    pdf.add_blank_line()

    pdf.add_heading2("30-Day Summary & Insights")
    pdf.add_blank_line()
    pdf.add_paragraph("After completing 30 days, answer these reflection questions:")
    pdf.add_blank_line()
    pdf.add_paragraph("Overall average anxiety level: ___/10")
    pdf.add_paragraph("Week 1 average: ___  Week 2: ___  Week 3: ___  Week 4: ___")
    pdf.add_paragraph("Trend: Getting better / Staying same / Getting worse (circle one)")
    pdf.add_blank_line()
    pdf.add_paragraph("My top 3 anxiety triggers:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Times of day when anxiety is worst:")
    pdf.add_paragraph("  [ ] Morning  [ ] Midday  [ ] Afternoon  [ ] Evening  [ ] Night")
    pdf.add_blank_line()
    pdf.add_paragraph("My top 3 most effective coping strategies:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Connection between sleep and anxiety (what I notice):")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Days with highest anxiety had this in common:")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Days with lowest anxiety had this in common:")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("One change I want to make based on these patterns:")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 5")
    pdf.add_separator()
    pdf.add_bullet("[ ] Start tracking today - even imperfect data is valuable")
    pdf.add_bullet("[ ] Set a daily reminder (phone alarm) to fill in the tracker")
    pdf.add_bullet("[ ] Complete weekly pattern reviews every Sunday")
    pdf.add_bullet("[ ] After 30 days, complete the summary and insights section")
    pdf.add_bullet("[ ] Share patterns with your therapist (if applicable)")
    pdf.add_bullet("[ ] Adjust your coping strategy plan based on what works")
    pdf.add_blank_line()



def add_chapter6(pdf):
    """Chapter 6: Coping Strategies Toolbox (8 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 6: COPING STRATEGIES TOOLBOX")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Having multiple coping strategies means you always have options. What works")
    pdf.add_paragraph("in one situation may not work in another. Build a diverse toolbox.")
    pdf.add_blank_line()

    pdf.add_heading2("50+ Coping Strategies by Category")
    pdf.add_blank_line()

    pdf.add_heading3("PHYSICAL STRATEGIES (Body-Based)")
    pdf.add_bullet("1. Go for a brisk walk or run (10-20 minutes)")
    pdf.add_bullet("2. Do progressive muscle relaxation")
    pdf.add_bullet("3. Take a cold shower or splash cold water on face")
    pdf.add_bullet("4. Practice yoga or gentle stretching")
    pdf.add_bullet("5. Dance to loud music")
    pdf.add_bullet("6. Do 20 jumping jacks or burpees")
    pdf.add_bullet("7. Squeeze a stress ball or ice cube")
    pdf.add_bullet("8. Garden or do physical chores")
    pdf.add_bullet("9. Take a warm bath with Epsom salts")
    pdf.add_bullet("10. Practice deep breathing exercises")
    pdf.add_bullet("11. Go swimming")
    pdf.add_bullet("12. Punch a pillow or shadow box")
    pdf.add_bullet("13. Drink herbal tea (chamomile, lavender)")
    pdf.add_blank_line()

    pdf.add_heading3("MENTAL STRATEGIES (Thought-Based)")
    pdf.add_bullet("14. Complete a thought record (Chapter 2)")
    pdf.add_bullet("15. Challenge catastrophic thinking")
    pdf.add_bullet("16. Practice acceptance: 'I notice I'm anxious. That's okay.'")
    pdf.add_bullet("17. Use positive affirmations")
    pdf.add_bullet("18. Visualize a safe, calm place in detail")
    pdf.add_bullet("19. Count backward from 100 by 7s")
    pdf.add_bullet("20. List 10 things you're grateful for")
    pdf.add_bullet("21. Read something engaging (not news)")
    pdf.add_bullet("22. Do a crossword puzzle or Sudoku")
    pdf.add_bullet("23. Practice mindfulness meditation (even 5 minutes)")
    pdf.add_bullet("24. Write in a journal (free-write for 10 minutes)")
    pdf.add_bullet("25. Repeat a calming mantra")
    pdf.add_blank_line()

    pdf.add_heading3("SOCIAL STRATEGIES (Connection-Based)")
    pdf.add_bullet("26. Call a trusted friend or family member")
    pdf.add_bullet("27. Text someone you care about")
    pdf.add_bullet("28. Hug someone (or a pet)")
    pdf.add_bullet("29. Go to a public place (coffee shop, park) to feel less alone")
    pdf.add_bullet("30. Attend a support group (in person or online)")
    pdf.add_bullet("31. Help someone else (volunteer, do a favor)")
    pdf.add_bullet("32. Play with children or animals")
    pdf.add_bullet("33. Join an online community related to your interests")
    pdf.add_bullet("34. Schedule a therapy appointment")
    pdf.add_bullet("35. Share how you're feeling with someone safe")
    pdf.add_bullet("36. Watch a comedy with someone")
    pdf.add_bullet("37. Cook or eat a meal with others")
    pdf.add_blank_line()

    pdf.add_heading3("CREATIVE STRATEGIES (Expression-Based)")
    pdf.add_bullet("38. Draw, paint, or color (adult coloring books)")
    pdf.add_bullet("39. Play a musical instrument")
    pdf.add_bullet("40. Write poetry or a short story")
    pdf.add_bullet("41. Take photographs of nature or things that interest you")
    pdf.add_bullet("42. Craft something (knitting, woodworking, origami)")
    pdf.add_bullet("43. Rearrange or redecorate a room")
    pdf.add_bullet("44. Cook or bake something new")
    pdf.add_bullet("45. Create a playlist for different moods")
    pdf.add_bullet("46. Write a letter (you don't have to send it)")
    pdf.add_bullet("47. Make a collage or vision board")
    pdf.add_blank_line()

    pdf.add_heading3("SENSORY STRATEGIES (Sense-Based)")
    pdf.add_bullet("48. Light a scented candle or use essential oils")
    pdf.add_bullet("49. Listen to calming music or nature sounds")
    pdf.add_bullet("50. Hold something with an interesting texture")
    pdf.add_bullet("51. Look at photos of nature, loved ones, or happy memories")
    pdf.add_bullet("52. Eat something with a strong flavor (sour candy, mint)")
    pdf.add_bullet("53. Wrap yourself in a weighted or heavy blanket")
    pdf.add_bullet("54. Sit in sunlight for 10 minutes")
    pdf.add_blank_line()

    pdf.add_heading2("Personal Coping Plan Builder")
    pdf.add_blank_line()
    pdf.add_paragraph("From the list above, choose your go-to strategies for each level:")
    pdf.add_blank_line()
    pdf.add_heading3("MILD ANXIETY (1-3/10) - Slight unease, some tension")
    pdf.add_paragraph("My strategies:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_heading3("MODERATE ANXIETY (4-6/10) - Noticeable distress, difficulty focusing")
    pdf.add_paragraph("My strategies:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_heading3("SEVERE ANXIETY (7-8/10) - Significant distress, functioning impaired")
    pdf.add_paragraph("My strategies:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_heading3("CRISIS LEVEL (9-10/10) - Panic, unable to function")
    pdf.add_paragraph("My strategies:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_paragraph("  Person to call: _________________ Phone: ___________________")
    pdf.add_blank_line()

    pdf.add_heading2("Coping Strategy Effectiveness Tracker")
    pdf.add_blank_line()
    pdf.add_paragraph("After trying strategies, rate their effectiveness for you:")
    pdf.add_blank_line()
    pdf.add_paragraph("Strategy              | Used When     | Anxiety Before | After | Rating")
    pdf.add_paragraph("----------------------|---------------|----------------|-------|--------")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_paragraph("______________________|_______________|____/10         |___/10 | 1-5")
    pdf.add_blank_line()
    pdf.add_paragraph("Rating: 1=Not helpful, 2=Slightly helpful, 3=Moderately helpful,")
    pdf.add_paragraph("        4=Very helpful, 5=Extremely helpful")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 6")
    pdf.add_separator()
    pdf.add_bullet("[ ] Read through all 54 coping strategies")
    pdf.add_bullet("[ ] Star or highlight 10-15 that appeal to you")
    pdf.add_bullet("[ ] Fill in your Personal Coping Plan for each anxiety level")
    pdf.add_bullet("[ ] Try at least 3 new strategies this week")
    pdf.add_bullet("[ ] Track effectiveness in the table above")
    pdf.add_bullet("[ ] Identify your top 5 'always works' strategies")
    pdf.add_blank_line()



def add_chapter7(pdf):
    """Chapter 7: Safety Planning & Crisis Resources (4 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 7: SAFETY PLANNING & CRISIS RESOURCES")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Sometimes anxiety escalates to crisis level. Having a plan in place BEFORE")
    pdf.add_paragraph("a crisis means you do not have to think clearly when you are at your worst.")
    pdf.add_blank_line()

    pdf.add_heading2("Personal Safety Plan Template")
    pdf.add_blank_line()
    pdf.add_paragraph("Complete this now, while you are calm. Keep a copy accessible.")
    pdf.add_blank_line()
    pdf.add_heading3("STEP 1: WARNING SIGNS")
    pdf.add_paragraph("I know I'm heading toward crisis when I notice:")
    pdf.add_paragraph("  Physical signs: ________________________________________________")
    pdf.add_paragraph("  Thoughts: ______________________________________________________")
    pdf.add_paragraph("  Behaviors: _____________________________________________________")
    pdf.add_paragraph("  Emotions: ______________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading3("STEP 2: INTERNAL COPING STRATEGIES")
    pdf.add_paragraph("Things I can do by myself to calm down (without contacting anyone):")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading3("STEP 3: SOCIAL CONTACTS FOR DISTRACTION")
    pdf.add_paragraph("People I can call or visit to take my mind off things:")
    pdf.add_paragraph("  Name: _____________________ Phone: ___________________")
    pdf.add_paragraph("  Name: _____________________ Phone: ___________________")
    pdf.add_paragraph("  Name: _____________________ Phone: ___________________")
    pdf.add_blank_line()

    pdf.add_heading3("STEP 4: PEOPLE I CAN ASK FOR HELP")
    pdf.add_paragraph("People I trust to tell when I'm in crisis:")
    pdf.add_paragraph("  Name: _____________________ Phone: ___________________")
    pdf.add_paragraph("  Name: _____________________ Phone: ___________________")
    pdf.add_paragraph("  Therapist: _________________ Phone: ___________________")
    pdf.add_blank_line()

    pdf.add_heading3("STEP 5: PROFESSIONAL RESOURCES")
    pdf.add_paragraph("If the above steps are not enough:")
    pdf.add_paragraph("  My therapist: _________________ Phone: ___________________")
    pdf.add_paragraph("  My doctor: ___________________ Phone: ___________________")
    pdf.add_paragraph("  Local emergency room: _________ Phone: ___________________")
    pdf.add_blank_line()

    pdf.add_heading3("STEP 6: MAKING MY ENVIRONMENT SAFE")
    pdf.add_paragraph("Things I can do to make my immediate environment safer:")
    pdf.add_paragraph("  _______________________________________________________________")
    pdf.add_paragraph("  _______________________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("Crisis Hotline Numbers")
    pdf.add_blank_line()
    pdf.add_paragraph("Save these in your phone RIGHT NOW:")
    pdf.add_blank_line()
    pdf.add_bullet("988 Suicide & Crisis Lifeline: Call or text 988 (24/7)")
    pdf.add_bullet("Crisis Text Line: Text HOME to 741741 (24/7)")
    pdf.add_bullet("NAMI Helpline: 1-800-950-6264 (M-F, 10am-10pm ET)")
    pdf.add_bullet("SAMHSA Helpline: 1-800-662-4357 (24/7, free referrals)")
    pdf.add_bullet("Veterans Crisis Line: Dial 988 then press 1")
    pdf.add_bullet("Trevor Project (LGBTQ+ youth): 1-866-488-7386")
    pdf.add_bullet("Disaster Distress Helpline: 1-800-985-5990")
    pdf.add_blank_line()
    pdf.add_paragraph("INTERNATIONAL:")
    pdf.add_bullet("International Association for Suicide Prevention: https://www.iasp.info")
    pdf.add_bullet("Find your country's crisis line at findahelpline.com")
    pdf.add_blank_line()

    pdf.add_heading2("When to Seek Professional Help Checklist")
    pdf.add_blank_line()
    pdf.add_paragraph("Seek professional help if ANY of these apply:")
    pdf.add_blank_line()
    pdf.add_bullet("[ ] Anxiety is interfering with work or school performance")
    pdf.add_bullet("[ ] You are avoiding activities or places you used to enjoy")
    pdf.add_bullet("[ ] Physical symptoms are concerning (chest pain, constant headaches)")
    pdf.add_bullet("[ ] You are using alcohol, drugs, or food to cope")
    pdf.add_bullet("[ ] Relationships are suffering due to anxiety")
    pdf.add_bullet("[ ] You have panic attacks")
    pdf.add_bullet("[ ] Sleep is consistently disrupted (less than 5 hours)")
    pdf.add_bullet("[ ] You feel hopeless or think about harming yourself")
    pdf.add_bullet("[ ] Self-help strategies are not providing enough relief")
    pdf.add_bullet("[ ] Anxiety has lasted longer than 6 months")
    pdf.add_blank_line()
    pdf.add_paragraph("TYPES OF PROFESSIONALS WHO TREAT ANXIETY:")
    pdf.add_bullet("Therapist/Counselor (CBT specialist recommended): Talk therapy")
    pdf.add_bullet("Psychiatrist: Medication evaluation and management")
    pdf.add_bullet("Psychologist: Testing, diagnosis, and specialized therapy")
    pdf.add_bullet("Primary Care Doctor: Initial evaluation, medication, referrals")
    pdf.add_blank_line()
    pdf.add_paragraph("HOW TO FIND A THERAPIST:")
    pdf.add_bullet("Psychology Today therapist finder: psychologytoday.com/us/therapists")
    pdf.add_bullet("Filter by: CBT specialty, anxiety expertise, your insurance")
    pdf.add_bullet("Ask your insurance company for in-network providers")
    pdf.add_bullet("Consider online therapy: BetterHelp, Talkspace, Cerebral")
    pdf.add_blank_line()

    pdf.add_heading2("Support Network Mapper")
    pdf.add_blank_line()
    pdf.add_paragraph("Map your support network. Who can you turn to for different needs?")
    pdf.add_blank_line()
    pdf.add_paragraph("EMOTIONAL SUPPORT (listens without judgment):")
    pdf.add_paragraph("  1. ___________________________ Relationship: ________________")
    pdf.add_paragraph("  2. ___________________________ Relationship: ________________")
    pdf.add_blank_line()
    pdf.add_paragraph("PRACTICAL HELP (drives you, helps with tasks):")
    pdf.add_paragraph("  1. ___________________________ Relationship: ________________")
    pdf.add_paragraph("  2. ___________________________ Relationship: ________________")
    pdf.add_blank_line()
    pdf.add_paragraph("PROFESSIONAL SUPPORT:")
    pdf.add_paragraph("  Therapist: _________________________ Phone: ________________")
    pdf.add_paragraph("  Doctor: ____________________________ Phone: ________________")
    pdf.add_blank_line()
    pdf.add_paragraph("FUN & DISTRACTION (makes me laugh, good company):")
    pdf.add_paragraph("  1. ___________________________ Relationship: ________________")
    pdf.add_paragraph("  2. ___________________________ Relationship: ________________")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 7")
    pdf.add_separator()
    pdf.add_bullet("[ ] Complete the Personal Safety Plan (do it NOW while calm)")
    pdf.add_bullet("[ ] Save all crisis numbers in your phone contacts")
    pdf.add_bullet("[ ] Tell at least one person you trust about your anxiety")
    pdf.add_bullet("[ ] Research therapists in your area (even if not ready to go yet)")
    pdf.add_bullet("[ ] Complete the Support Network Mapper")
    pdf.add_bullet("[ ] Keep a copy of your safety plan somewhere easily accessible")
    pdf.add_blank_line()



def add_chapter8(pdf):
    """Chapter 8: Action Plans & Goal Setting (8 pages)"""
    pdf.add_page_break()
    pdf.add_heading1("CHAPTER 8: ACTION PLANS & GOAL SETTING")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Recovery from anxiety is not about eliminating all fear. It is about")
    pdf.add_paragraph("building your tolerance for discomfort and gradually reclaiming activities")
    pdf.add_paragraph("that anxiety has taken from you.")
    pdf.add_blank_line()

    pdf.add_heading2("Exposure Hierarchy Builder")
    pdf.add_blank_line()
    pdf.add_paragraph("Exposure therapy works by gradually facing feared situations, starting")
    pdf.add_paragraph("with the least scary and working up. Build your personal hierarchy:")
    pdf.add_blank_line()
    pdf.add_paragraph("What anxiety prevents me from doing:")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Rate each step on the Fear Thermometer (0-100):")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 10 (90-100 fear): _________________________________________")
    pdf.add_paragraph("  (Your ultimate goal - hardest step)")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 9 (80-90 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 8 (70-80 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 7 (60-70 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 6 (50-60 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 5 (40-50 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 4 (30-40 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 3 (20-30 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 2 (10-20 fear):   _________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("LEVEL 1 (0-10 fear):    _________________________________________")
    pdf.add_paragraph("  (Start here - easiest step)")
    pdf.add_blank_line()
    pdf.add_paragraph("RULES FOR EXPOSURE:")
    pdf.add_bullet("Start at Level 1 and stay until anxiety drops by 50%")
    pdf.add_bullet("Do not move to next level until current level feels manageable")
    pdf.add_bullet("Repeat each level 3-5 times before moving up")
    pdf.add_bullet("Never force yourself past a 7/10 anxiety without professional guidance")
    pdf.add_bullet("Some temporary discomfort is expected and normal")
    pdf.add_blank_line()

    pdf.add_heading2("Avoidance Behavior Tracker")
    pdf.add_blank_line()
    pdf.add_paragraph("Avoidance maintains anxiety. Track what you are avoiding and start")
    pdf.add_paragraph("facing those situations gradually:")
    pdf.add_blank_line()
    pdf.add_paragraph("Situation I Avoid    | Why I Avoid It      | Fear Level | Faced It? | Result")
    pdf.add_paragraph("---------------------|---------------------|------------|-----------|-------")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_paragraph("_____________________|_____________________|____/10     |  Y / N    |_______")
    pdf.add_blank_line()
    pdf.add_paragraph("PATTERN: When I face the thing I avoid, what usually happens?")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("(Usually: It was not as bad as I predicted.)")
    pdf.add_blank_line()

    pdf.add_heading2("Values-Based Goal Setting")
    pdf.add_blank_line()
    pdf.add_paragraph("Anxiety narrows your world. Values expand it. What matters to you?")
    pdf.add_blank_line()
    pdf.add_paragraph("Rate importance (1-10) and satisfaction (1-10) for each area:")
    pdf.add_blank_line()
    pdf.add_paragraph("LIFE AREA           | Importance | Satisfaction | Gap")
    pdf.add_paragraph("--------------------|------------|--------------|----")
    pdf.add_paragraph("Relationships       | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Work/Career         | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Health/Fitness      | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Fun/Recreation      | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Personal Growth     | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Family              | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Spirituality        | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Community           | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Creativity          | ___/10     | ___/10       | ___")
    pdf.add_paragraph("Financial Security  | ___/10     | ___/10       | ___")
    pdf.add_blank_line()
    pdf.add_paragraph("Biggest gaps (where importance far exceeds satisfaction):")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("How is anxiety keeping me from living according to my values?")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_paragraph("_______________________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("90-Day Anxiety Management Plan")
    pdf.add_blank_line()
    pdf.add_paragraph("Set specific, measurable goals for the next 90 days:")
    pdf.add_blank_line()
    pdf.add_heading3("MONTH 1: FOUNDATION (Learn & Practice)")
    pdf.add_paragraph("Goal 1: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Goal 2: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()

    pdf.add_heading3("MONTH 2: BUILD (Apply & Expand)")
    pdf.add_paragraph("Goal 1: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Goal 2: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()

    pdf.add_heading3("MONTH 3: MAINTAIN (Sustain & Challenge)")
    pdf.add_paragraph("Goal 1: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()
    pdf.add_paragraph("Goal 2: _______________________________________________________")
    pdf.add_paragraph("  Specific actions: _____________________________________________")
    pdf.add_paragraph("  How I'll measure progress: ____________________________________")
    pdf.add_blank_line()

    pdf.add_heading3("90-DAY REVIEW:")
    pdf.add_paragraph("Current anxiety baseline (average): ___/10")
    pdf.add_paragraph("90-day target: ___/10")
    pdf.add_paragraph("Situations I want to be able to handle:")
    pdf.add_paragraph("  1. ___________________________________________________________")
    pdf.add_paragraph("  2. ___________________________________________________________")
    pdf.add_paragraph("  3. ___________________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("Daily Anxiety Management Routine")
    pdf.add_blank_line()
    pdf.add_paragraph("Build these habits into your daily schedule:")
    pdf.add_blank_line()
    pdf.add_heading3("MORNING (5-10 minutes):")
    pdf.add_bullet("[ ] 3 minutes of deep breathing before getting out of bed")
    pdf.add_bullet("[ ] Set intention: 'Today I will practice _______________'")
    pdf.add_bullet("[ ] Rate morning anxiety level: ___/10")
    pdf.add_blank_line()
    pdf.add_heading3("MIDDAY (5 minutes):")
    pdf.add_bullet("[ ] Body scan: Where am I holding tension?")
    pdf.add_bullet("[ ] 5-4-3-2-1 grounding if needed")
    pdf.add_bullet("[ ] Brief walk or stretching break")
    pdf.add_blank_line()
    pdf.add_heading3("EVENING (10-15 minutes):")
    pdf.add_bullet("[ ] Fill in daily anxiety tracker")
    pdf.add_bullet("[ ] Complete one thought record (if applicable)")
    pdf.add_bullet("[ ] Progressive muscle relaxation or body scan")
    pdf.add_bullet("[ ] 3 things that went okay today:")
    pdf.add_paragraph("     1. _______________________________________________________")
    pdf.add_paragraph("     2. _______________________________________________________")
    pdf.add_paragraph("     3. _______________________________________________________")
    pdf.add_blank_line()

    pdf.add_heading2("YOUR ACTION ITEMS - Chapter 8")
    pdf.add_separator()
    pdf.add_bullet("[ ] Build your exposure hierarchy for one feared situation")
    pdf.add_bullet("[ ] Identify 3 avoidance behaviors you want to challenge")
    pdf.add_bullet("[ ] Complete the values assessment")
    pdf.add_bullet("[ ] Set 2 specific goals for the next 30 days")
    pdf.add_bullet("[ ] Implement the daily routine starting tomorrow")
    pdf.add_bullet("[ ] Schedule a check-in with yourself in 30 days to assess progress")
    pdf.add_blank_line()



def add_next_steps(pdf):
    """Final Next Steps page"""
    pdf.add_page_break()
    pdf.add_heading1("NEXT STEPS")
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("Congratulations on completing this workbook. Managing anxiety is a skill,")
    pdf.add_paragraph("and like any skill, it improves with consistent practice.")
    pdf.add_blank_line()
    pdf.add_heading2("Your Immediate Actions:")
    pdf.add_blank_line()
    pdf.add_bullet("1. Start the Daily Anxiety Tracker today (Chapter 5)")
    pdf.add_bullet("2. Practice one breathing technique daily (Chapter 3)")
    pdf.add_bullet("3. Complete at least one thought record per day (Chapter 2)")
    pdf.add_bullet("4. Set up your worry time (Chapter 4)")
    pdf.add_bullet("5. Fill in your Safety Plan (Chapter 7)")
    pdf.add_blank_line()
    pdf.add_heading2("Remember:")
    pdf.add_blank_line()
    pdf.add_bullet("Progress is not linear. Bad days do not erase good days.")
    pdf.add_bullet("Self-help workbooks complement but do not replace professional care.")
    pdf.add_bullet("Be patient with yourself. Anxiety took time to develop; it takes time to heal.")
    pdf.add_bullet("Celebrate small wins. Every faced fear is a victory.")
    pdf.add_bullet("You are not broken. You are a human with a sensitive nervous system.")
    pdf.add_blank_line()
    pdf.add_separator()
    pdf.add_blank_line()
    pdf.add_paragraph("ANXIETY & STRESS MANAGEMENT WORKBOOK")
    pdf.add_paragraph("By Daniel Tesfamariam")
    pdf.add_blank_line()
    pdf.add_paragraph("Copyright 2024. All rights reserved.")
    pdf.add_paragraph("This workbook is for educational purposes only.")
    pdf.add_blank_line()


def generate_anxiety_workbook():
    pdf = generate_anxiety_workbook_title()
    add_chapter1(pdf)
    add_chapter2(pdf)
    add_chapter3(pdf)
    add_chapter4(pdf)
    add_chapter5(pdf)
    add_chapter6(pdf)
    add_chapter7(pdf)
    add_chapter8(pdf)
    add_next_steps(pdf)

    output_path = '/projects/sandbox/CLAUDE/etsy-business-builder/pdf-output/02-Anxiety-Stress-Management-Workbook.pdf'
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    size = pdf.save(output_path)

    print("=" * 60)
    print("  ANXIETY & STRESS MANAGEMENT WORKBOOK")
    print("  By Daniel Tesfamariam")
    print("=" * 60)
    print(f"  PDF Generated Successfully!")
    print(f"  Output: {output_path}")
    print(f"  Size: {size / 1024:.1f} KB")
    print(f"  Pages: {len(pdf.pages)}")
    if len(pdf.pages) >= 60:
        print(f"  TARGET MET: {len(pdf.pages)} pages (goal: 60-80)")
    else:
        print(f"  NOTE: {len(pdf.pages)} pages generated (goal: 60-80)")
    print()
    return output_path


# Rename the first function to avoid conflict
def generate_anxiety_workbook_title():
    pdf = PurePDF(title="Anxiety & Stress Management Workbook", author="Daniel Tesfamariam")

    # === TITLE PAGE ===
    pdf.add_blank_line()
    pdf.add_blank_line()
    pdf.add_blank_line()
    pdf.add_title("ANXIETY & STRESS MANAGEMENT WORKBOOK")
    pdf.add_blank_line()
    pdf.add_heading2("Evidence-Based CBT Techniques, Thought Records,")
    pdf.add_heading2("Breathing Exercises & Daily Tracking Tools")
    pdf.add_blank_line()
    pdf.add_blank_line()
    pdf.add_paragraph("By Daniel Tesfamariam")
    pdf.add_blank_line()
    pdf.add_separator()
    pdf.add_paragraph("This workbook provides practical, evidence-based tools to help you")
    pdf.add_paragraph("understand, manage, and reduce anxiety in your daily life.")
    pdf.add_blank_line()
    pdf.add_separator()
    pdf.add_paragraph("Copyright 2024 Daniel Tesfamariam. All rights reserved.")
    pdf.add_paragraph("This workbook is for educational purposes only and does not replace")
    pdf.add_paragraph("professional mental health treatment.")

    # === TABLE OF CONTENTS ===
    pdf.add_page_break()
    pdf.add_heading1("TABLE OF CONTENTS")
    pdf.add_blank_line()
    pdf.add_paragraph("Chapter 1: Understanding Anxiety ............................ 3")
    pdf.add_paragraph("Chapter 2: CBT Thought Records ............................. 11")
    pdf.add_paragraph("Chapter 3: Breathing & Grounding Techniques ................ 23")
    pdf.add_paragraph("Chapter 4: Worry Management System ......................... 31")
    pdf.add_paragraph("Chapter 5: Daily Anxiety Tracker ........................... 41")
    pdf.add_paragraph("Chapter 6: Coping Strategies Toolbox ....................... 53")
    pdf.add_paragraph("Chapter 7: Safety Planning & Crisis Resources .............. 61")
    pdf.add_paragraph("Chapter 8: Action Plans & Goal Setting ..................... 65")
    pdf.add_paragraph("Next Steps ................................................. 73")
    pdf.add_blank_line()
    pdf.add_separator()

    return pdf


if __name__ == '__main__':
    generate_anxiety_workbook()
